backend:
  name: github
  repo: vbhbv/Mjwll
  branch: main 

publish_mode: editorial_workflow

media_folder: "images" 
public_folder: "/images"

collections:
  - name: "articles"
    label: "المقالات"
    folder: "_articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "التاريخ", name: "date", widget: "datetime"}
      - {label: "محتوى المقال", name: "body", widget: "markdown"}
      
