backend:
  name: github
  repo: vbhbv/Mjwll
  branch: main
  site_domain: vbhbv.github.io/Mjwll 
  base_url: https://api.netlify.com
  auth_endpoint: auth

# الأسطر الجديدة المطلوبة هنا:
media_folder: "images/uploads"   # **مهم:** تحديد مجلد لحفظ الصور التي ترفعها (ستحتاج لإنشاء هذا المجلد)
public_folder: "/images/uploads" # **مهم:** المسار العام للوصول للصور على موقعك

# تعريف ملفات المحتوى (Collections)
collections:
  - name: "articles"
    label: "مقالات الموقع" 
    folder: "/"
    create: true
    slug: "article-{{slug}}" 
    extension: "html"
    format: "frontmatter"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "محتوى المقال", name: "body", widget: "markdown"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime", required: false}
      - {label: "صورة الغلاف", name: "image", widget: "image", required: false} 
      
