backend:
  name: github
  repo: vhbhv/Mjwll
  branch: main
  auth_scope: repo  # هذا السطر يظهر حقل البريد وكلمة المرور

# --- إعدادات تدفق العمل التحريري ---
publish_mode: editorial_workflow

# --- إعدادات الوسائط والصور ---
media_folder: "static/images"
public_folder: "/images"

# --- تعريف المجموعات (المقالات) ---
collections:
  - name: "posts"
    label: "مقالات ثقافية"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "التاريخ", name: "date", widget: "datetime"}
      - {label: "الوصف", name: "description", widget: "text"}
      - {label: "محتوى المقال", name: "body", widget: "markdown"}
      
